### ISSUE TITLE
Exception when installing plugins on 8.x

### ISSUE THREAD

**Issue by Guerteltier** [elastic/elastic-github-actions#32]
https://github.com/asozialesnetzwerk/an-website/blob/8b5b301575416fe475e3bb88c760c54cd4c5c1fb/.github/workflows/release.yml#L129-L143
https://github.com/asozialesnetzwerk/an-website/actions/runs/6369096572/job/17289014819
```
-> Installing analysis-icu
-> Downloading analysis-icu from elastic
-> Failed installing analysis-icu
-> Rolling back analysis-icu
-> Rolled back analysis-icu
Exception in thread "main" java.nio.file.AccessDeniedException: /usr/share/elasticsearch/plugins/.installing-11365180841595527243
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:438)
	at java.base/java.nio.file.Files.createDirectory(Files.java:699)
	at java.base/java.nio.file.TempFileHelper.create(TempFileHelper.java:134)
	at java.base/java.nio.file.TempFileHelper.createTempDirectory(TempFileHelper.java:171)
	at java.base/java.nio.file.Files.createTempDirectory(Files.java:975)
	at org.elasticsearch.plugins.cli.InstallPluginAction.stagingDirectory(InstallPluginAction.java:824)
	at org.elasticsearch.plugins.cli.InstallPluginAction.unzip(InstallPluginAction.java:771)
	at org.elasticsearch.plugins.cli.InstallPluginAction.execute(InstallPluginAction.java:252)
	at org.elasticsearch.plugins.cli.InstallPluginCommand.execute(InstallPluginCommand.java:89)
	at org.elasticsearch.common.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:54)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:85)
	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:[94](https://github.com/asozialesnetzwerk/an-website/actions/runs/6369096572/job/17289014819#step:6:95))
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:85)
	at org.elasticsearch.cli.Command.main(Command.java:50)
	at org.elasticsearch.launcher.CliToolLauncher.main(CliToolLauncher.java:64)
```

**Comment by picandocodigo** [comment]
Hi @Guerteltier,
We recently merged a change that addresses installing plugins. I'm going to close this issue as resolved, but don't hesitate to open a new one if you encounter further problems. 
Thanks!
